export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_WEEK = 'UPDATE_WEEK';
export const UPDATE_WEEK_NUMBER = 'UPDATE_WEEK_NUMBER';
export const SET_WEEK_NUMBER = 'SET_WEEK_NUMBER';
export const SET_LOADING = 'SET_LOADING';
